AllCops:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'Gemfile'

Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
Metrics/AbcSize:
  Enabled: false
